server:
  port: 8080
spring:
  application:
    name: sunny #项目名称
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sunny?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
#  redis:
#    database: 2
#    host: 192.168.8.88
#    port: 6379
#    password:
######Mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
####################################
#生存时间 配置
jwt:
  config:
    key: sunny
    ttl: 3600000
####################################
